#!/usr/bin/env python3
"""
Convert an image to an RGB565 C header for blitting with LovyanGFX.

    python tools/img2rgb565.py assets/geass.png src/menu/geass_image.h --size 168

Transparent pixels are composited onto black, so the artwork blends into the
device's black screen. Output is a flat const uint16_t array plus its
dimensions, in the standard R5G6B5 bit order (cast to lgfx::rgb565_t at the
call site so LovyanGFX handles panel byte-swapping).
"""

import argparse
import os
from PIL import Image


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("output")
    ap.add_argument("--size", type=int, default=168,
                    help="target height in px; width scales to keep aspect")
    ap.add_argument("--name", default="GEASS", help="C identifier prefix")
    args = ap.parse_args()

    im = Image.open(args.input).convert("RGBA")

    # Trim fully-transparent margins so the subject fills the frame.
    bbox = im.getbbox()
    if bbox:
        im = im.crop(bbox)

    # Scale to the target height, keeping aspect ratio.
    w, h = im.size
    tw = max(1, round(w * args.size / h))
    im = im.resize((tw, args.size), Image.LANCZOS)

    # Composite over black.
    black = Image.new("RGBA", im.size, (0, 0, 0, 255))
    im = Image.alpha_composite(black, im).convert("RGB")

    w, h = im.size
    px = im.load()

    vals = []
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            vals.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))

    guard = os.path.basename(args.output).upper().replace(".", "_")
    with open(args.output, "w") as f:
        f.write(f"// Generated by tools/img2rgb565.py from {os.path.basename(args.input)}\n")
        f.write(f"// {w}x{h}, RGB565. Do not edit by hand.\n")
        f.write("#pragma once\n#include <cstdint>\n\n")
        f.write(f"namespace {args.name.lower()}_img {{\n")
        f.write(f"constexpr int WIDTH  = {w};\n")
        f.write(f"constexpr int HEIGHT = {h};\n")
        f.write(f"inline constexpr uint16_t DATA[WIDTH * HEIGHT] = {{\n")
        for i in range(0, len(vals), 12):
            f.write("  " + ",".join(f"0x{v:04X}" for v in vals[i:i + 12]) + ",\n")
        f.write("};\n")
        f.write(f"}}  // namespace {args.name.lower()}_img\n")

    kb = len(vals) * 2 / 1024
    print(f"wrote {args.output}: {w}x{h}, {kb:.1f} KB of flash")


if __name__ == "__main__":
    main()
